# This workflow will deploy the application to the running environment after a successful merge to main

name: deploy

on:
#   workflow_run:
#     workflows: [Test] # Triggered by the test workflow
#     types: [completed] # The test workflow must complete
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  on-success:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only when test completed successfully 
    defaults:
        run:
          working-directory: ./topics-project
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.2.0'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the Next.js project
        run: npm run build
        env:
            NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Upload Next.js build artifact
        uses: actions/upload-artifact@v2
        with:
          name: nextjs_build
          path: .next

      - name: Congifure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.JOHAN_GITHUB_ACTION_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.JOHAN_GITHUB_ACTION_SECRET_KEY }}
          aws-region: "us-east-1"

      - name: Upload Next.js build to AWS S3
        run: aws s3 sync .next s3://your-bucket-name

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name sparta \
          --source-bundle S3Bucket="johandelao-sparta",S3Key="johan_sparta_deploy-${{ github.sha }}.zip" \
          --version-label "v${{ github.sha }}" \
          --description "Next.js deployment"

          aws elasticbeanstalk update-environment --environment-name your-environment-name --version-label "v${{ github.sha }}"
