name: Test
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.2.0
        
    - name: Install Dependencies
      run: npm i --prefix topics-project

    - name: Build Application
      run: npm run build --prefix topics-project
      
    - name: Run unit and integration tests
      run: npm run test --prefix topics-project

    - name: Generate Code Coverage Report
      run: npm run test --prefix topics-project -- --coverage

    - name: Launch Application
      run: npm run start --prefix topics-project &

    - name: Run e2e Tests
      run: npx playwright test topics-project
